using Unity.Behavior;

[BlackboardEnum]
public enum AbilityNames
{
    // HUNTER
    HUNTER_CROSSBOW,
    HUNTER_CHARGED_CROSSBOW,
    HUNTER_ROLL,
    HUNTER_BOMB,

    // MAGE
    MAGE_EAGLE,
    MAGE_WEREBEAR,
    MAGE_ZOLTRAAK,

    // CULTIST
    CULTIST_FIREBALL,
    CULTIST_TWISTED_TENTACLES,

    WARRIOR_CHARGE,
    WARRIOR_SWORD_SLASH_DOWN,
    WARRIOR_SWORD_SLASH_UP,
    WARRIOR_JUMP_SLAM,
    WARRIOR_BLOCK,

    // ASSISTS
    WARRIOR_CHARGE_ATTACK_ASSIST,
    HUNTER_DASH_ATTACK_ASSIST,

    // HUNTER CONTINUED
    HUNTER_SWORD_ATTACK,

    // WARRIOR CONTINUED
    WARRIOR_CHAIN,

    // HUNTER CONTINUED omg...
    HUNTER_SWORD_AIR_ATTACK

    // Add more abilities as needed
}